# Generated by Django 6.0.2

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Example",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid6.uuid6,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "example",
                "abstract": False,
            },
        ),
    ]
